apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
   name: fargateprofiles.jicomusic.com
spec:
   scope: Namespaced
   group: jicomusic.com
   versions:
     - name: v1
       served: true
       storage: true
   names:
     kind: FargateProfile
     plural: fargateprofiles
     singular: fargateprofile
     shortNames:
     - fp
   #preserveUnknownFields: false
   validation:
     openAPIV3Schema:
       type: object
       properties:
         spec:
           type: object
           properties:
             subnets:
               type: array
               pattern: '(subnet-)[0-9a-z]{17}'
             podExecutionRoleArn:
               type: string
             tags:
               type: object
             selectors:
               type: array
               maxItems: 5
               properties:
                 namespace:
                   type: array
                   properties:
                     labels:
                       type: object
                       maxItems: 5