---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: kopf-sa
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kopf-cluster-role
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [jicomusic.com]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get]

  - apiGroups: [jicomusic.com]
    resources: [fargateprofiles]
    verbs: ['*']
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kopf-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kopf-cluster-role
subjects:
  - kind: ServiceAccount
    name: kopf-sa
    namespace: default
  - kind: ServiceAccount
    name: fargate
    namespace: default