apiVersion: jicomusic.com/v1
kind: FargateProfile
metadata:
  name: new-profile-7
spec:
  subnets: [subnet-075aa287882d71709, subnet-0b36ca4d53f742857]
  podExecutionRoleArn: arn:aws:iam::820537372947:role/eksctl-appmesh-workshop-cl-FargatePodExecutionRole-ZBZNZ6OBYOHE
  selectors:
  - namespace: default
    labels:
      foo: bar
      red: black
      green: blue
      orange: red
      purple: yellow
      green: white
  - namespace: system
    labels:
      foo: bar
  - namespace: hello
    labels:
      foo: bar
  - namespace: world
    labels:
      foo: bar
  tags:
      red: black
      green: blue